### ISSUE TITLE
Performance Issues - Multiple Cacheless Generate Calls

### ISSUE THREAD

**Issue by Ryul0rd** [1rgs/jsonformer#13] opened 2023-05-05 08:02 UTC
Coming here from [this issue](https://github.com/huggingface/transformers/issues/23102) over on transformers. Looks like I'm no longer getting the error I was getting earlier but there are still performance issues.

Taking a look at the code, the key issue is that it's calling generate once for every value and there's no caching the key and value tensors so a ton of work is being done multiple times. On my machine the example code takes about 4 seconds to generate when using gpt2 as a model when it normally takes about 0.25 seconds to generate a comparable amount of text with free form generation.

I see two solutions:
1. Cache the keys and values so that work isn't getting redone every generate call. I thought the transformers library had some built in functionality for this but I went looking just now and couldn't find it. Hopefully I'm missing something.
2. Use the approach in [my implementation](https://github.com/Ryul0rd/llm-json-output). I create a [DFA](https://en.wikipedia.org/wiki/Deterministic_finite_automaton) for the desired schema then make a single call to generate, using the DFA to determine which tokens are legal continuations each time the callable passed as the `prefix_allowed_tokens_fn` argument in generate gets called. My approach does have the problem mentioned in the other issue, which is that it's very slow when implemented in Python so it would need to be done in C/C++/Rust. It would also basically be a complete rewrite of this library.

**Comment by 1rgs** [comment] 2023-05-08 03:09
@Ryul0rd I ran a bunch of performance tests, running generate with max_new_tokens=1 100 times in a loop is not that much slower than running generate once with max_new_tokens=100

The tranformers library's [sample implementation](https://github.com/huggingface/transformers/blob/04ab5605fbb4ef207b10bf2772d88c53fc242e83/src/transformers/generation/utils.py#L2509) seems to be doing this in Python, inside a while loop. 

However, I did track down the source of the slowness, which was caused by the non-vectorized implementation of the number logit warper. This should be fixed in 0.11.0, with much better performance (I'm seeing a 4x speedup on the large example in the readme)

**Closed by 1rgs** 2023-05-08 03:09 UTC

**Comment by Ryul0rd** [comment] 2023-05-08 04:17
I just ran the 1 token 100 times vs the 100 tokens 1 time test and using GPT2 on CPU there's a ~45x speed difference.
